[project]
name = "semestre-vii"
version = "0.1.0"
description = "Código, actividades y utilidades ejecutables del semestre VII"
readme = "README.md"
authors = [
    { name = "Fernando Leon Franco", email = "fernanlee2131@gmail.com" }
]
requires-python = ">=3.14.6"
dependencies = [
    "duckdb>=1.5.5",
    "httpx>=0.28.1",
    "polars>=1.44.1",
    "pyarrow>=25.0.1",
]

[project.scripts]
semestre-vii = "semestre_vii.__main__:main"
ecobici = "semestre_vii.mineria_de_datos.actividades.ecobici.__main__:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
